
[[Systems]]
  Name = "t01"
  Usage = "production"
  Tags = []
  Lang = "en"
  User = "user1"
  Client = "100"
  Server = "host1.example.com"
  Sysnr = "01"

[[TableMetrics]]
  Name = "sap_users"
  Help = "sm04 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "TH_USER_LIST"
  AllServers = true
  Table = "USRLIST"
  [TableMetrics.Params]
  [TableMetrics.RowCount]
    type = [4]
    guiversion = ["76", "75", "74"]
    mandt = ["000", "090", "100", "400"]
  [TableMetrics.RowFilter]

[[TableMetrics]]
  Name = "sap_lock_entries"
  Help = "sm12 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "ENQUE_READ"
  AllServers = false
  Table = "ENQ"
  [TableMetrics.Params]
    GARG = ""
    GCLIENT = ""
    GNAME = ""
    GUNAME = ""
  [TableMetrics.RowCount]
    gclient = ["total", "000", "090", "100", "400"]
  [TableMetrics.RowFilter]

[[TableMetrics]]
  Name = "sap_processes"
  Help = "sm50 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "TH_WPINFO"
  AllServers = true
  Table = "WPLIST"
  [TableMetrics.Params]
    SRVNAME = ""
  [TableMetrics.RowCount]
    WP_TYP = ["dia", "bgd", "upd", "up2"]
    WP_TABLE = ["dbvm", "dbvl", "ma61v", "mdup"]
  [TableMetrics.RowFilter]
    WP_STATUS = ["on hold", "running"]

[[FieldMetrics]]
  Name = "sap_kernel_info"
  Help = "SAP kernel and db client info"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "TH_SAPREL2"
  fieldLabels = ["kern_rel", "kern_dblib", "kern_patchlevel"]

[[FieldMetrics]]
 Name = "sap_stapi_version"
 Help = "SAP ST-A/Pi version info"
 MetricType = "gauge"
 TagFilter = []
 FunctionModule = "ANST_OCS_GET_COMPONENT_STATE"
 FieldLabels = ["ev_comp_rel", "ev_comp_spp_level"]
 AllServers = false
 [FieldMetrics.Params]
   IV_COMPONENT = "ST-A/PI"
